syntax = "proto3";

package subscription;

service SubscriptionService {
  rpc Subscribe(SubscribeRequest) returns (SubscribeResponse);
  
  rpc Confirm(ConfirmRequest) returns (ConfirmResponse);
  
  rpc Unsubscribe(UnsubscribeRequest) returns (UnsubscribeResponse);
  
  rpc GetSubscriptions(GetSubscriptionsRequest) returns (GetSubscriptionsResponse);
}

message SubscribeRequest {
  string email = 1;
  string repo = 2;
}

message SubscribeResponse {
  string message = 1;
}

message ConfirmRequest {
  string token = 1;
}

message ConfirmResponse {
  string message = 1;
}

message UnsubscribeRequest {
  string token = 1;
}

message UnsubscribeResponse {
  string message = 1;
}

message GetSubscriptionsRequest {
  string email = 1;
}

message GetSubscriptionsResponse {
  repeated Subscription subscriptions = 1;
}

message Subscription {
  string email = 1;
  string repo = 2;
  bool confirmed = 3;
  string last_seen_tag = 4;
}

message ErrorResponse {
  int32 code = 1;
  string message = 2;
  string details = 3;
}